In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1 - sig(z))

In [5]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
lr = 0.1
weights, bias

(array([[0.13985319],
        [0.52666558]]), array([-0.9400841]))

In [6]:
# forward propagation without any hidden layer
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0, weights) + bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    first_two.shape
    
    changes = np.array([[0.0],[0.0]])

    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]
    weights = weights - lr*changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1
    bias = bias - lr * bias_change
output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[5.48446985],
        [5.48446986]]), array([-8.31937451]), array([[2.43688879e-04],
        [5.54668805e-02],
        [5.54668799e-02],
        [9.33984186e-01]]))

In [7]:
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0, weights) + bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    first_two.shape
    
    changes = np.dot(output0.T,first_two)
    weights = weights - lr*changes
    bias_change = np.sum(first_two)
    bias = bias - lr * bias_change
output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[6.27586532],
        [6.27586532]]), array([-9.50360616]), array([[7.45768266e-05],
        [3.81350285e-02],
        [3.81350285e-02],
        [9.54701486e-01]]))